services:
  api:
    build:
      context: .
      dockerfile: DockerFile
    container_name: api
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
    networks:
      - app-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "StrongPass!123"
    ports:
      - "1433:1433"
    networks:
      - app-network
    volumes:
      - sql_data:/var/opt/mssql

networks:
  app-network:
    driver: bridge

volumes:
  sql_data:
